artifact_location: file:///Users/henry/Desktop/final-project/ai/finance-segmentation-api/mlruns/0
creation_time: 1747621384716
experiment_id: '0'
last_update_time: 1747621384716
lifecycle_stage: active
name: Default
