artifact_location: file:///Users/henry/Desktop/final-project/ai/finance-segmentation-api/mlruns/185642500988300395
creation_time: 1747621384719
experiment_id: '185642500988300395'
last_update_time: 1747621384719
lifecycle_stage: active
name: Model Inspection
